spring.application.name=xml-parser

# Postgres DB Config
spring.datasource.url=jdbc:postgresql://localhost:5434/xml_parser_db
spring.datasource.username=brandon
spring.datasource.password=FarideDev10@

# JPA Config
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.properties.hibernate.hbm2ddl.auto=debug

# environment var
    # OS scope
xml.parser.batch-size=${XML_PARSER_BATCH_SIZE:100}
    # project scope
#xml.parser.batch-size=100





